function d=ld2_method_data_1_4(step)
    d=struct("goal", "", "theory",emptystr(0,1), "method",emptystr(0,1), "formulas",emptystr(0,1), "check",emptystr(0,1), "mistakes",emptystr(0,1), "questions",emptystr(0,1), "source",emptystr(0,1));
    select step
    case 1 then
        d.goal="Priskirti individualų variantą ir suprasti, kas bus matuojama.";
        d.theory=["Sąrašo numeris n nuo 1 iki 64 vienareikšmiškai nustato visų RC, RL ir RLC bandymų parametrus. Tai nėra atsitiktinis parinkimas: tas pats n kaskart duoda tą patį LD2-Vnn variantą. Matavimai, pavyzdžiai ir ataskaita naudoja tą patį rinkinį.";"Iš pirminio aprašo išlaikytos 9 V RC/RL ir 5 V RLC efektinės įtampos, C2 = 4,7 µF ir L1 = 0,5 H. Individualios rezistorių, RLC L3/C4 ir RC/RL dažnių reikšmės yra naujas metodinis priedas virtualiam darbui, ne spėjimas apie tikro modulio elementus.";"LD2 yra šio programinio stendo vardas pagal ankstesnį 6 puslapių aprašą. Dalyko TF-EA-2025-07 apraše ši RC/RL/RLC tematika siejasi su 9 ir 10 laboratoriniais darbais. Ji nėra I semestro 2 laboratorinis darbas „Įtampos ir srovės matavimas“.";"64 LD2 variantų bankas atskiras nuo pridėtos praktinių darbų medžiagos 60 variantų banko. Šie numeriai nereiškia tų pačių uždavinių."];
        d.method=["1. Spauskite [B01]. [F01] įrašykite savo eilės numerį 1–64; [F02] vardą ir pavardę; [F03] grupę. Patvirtinkite OK.";"2. Patikrinkite patvirtinimą: „Sąrašo Nr. n → LD2-Vnn“. [B39] patikrinkite visas priskirtas reikšmes.";"3. [B43] rodo visą 64 variantų banką. [B42] paaiškina kontaktus; [B45] – valdiklius.";"4. Perskaitykite šio lango bendrąją atmintinę. [B38] paaiškina šaltinius ir metodinius pakeitimus.";"5. [B04] patikrinkite etapą. [B05] išsaugokite pirmą .sod failą. [B36] pereikite į E02."];
        d.formulas=["n = sveikas skaičius nuo 1 iki 64.";"a = floor((n−1)/8)+1; b = modulo(n−1,8)+1. Šie indeksai parenka 8×8 variantų lentelę."];
        d.check=["Antraštėje matomas jūsų LD2-Vnn, vardas ir grupė.";"Parametrai keičiasi tik per B01 keičiant numerį; tada ankstesni bandymai nesujungiami su naujais."];
        d.mistakes=["Įvestas 0 arba 65: [B01] pataisykite į 1–64.";"Įvesta „17a“: [F01] rašykite tik 17.";"Suklydote tik varde: palikite tą patį numerį ir pakeiskite vardą – matavimai lieka."];
        d.questions=["Kuo efektinė įtampa skiriasi nuo amplitudės?";"Kodėl pakeitus varianto numerį negalima palikti seno varianto matavimų?"];
        d.source=["[S1] p. 3–6: RC, RL ir RLC darbų turinys.";"[S2] dalyko aprašas: temos 13–14, darbai 9–10.";"[N] 64 variantai, numeriai ir ataskaitos tvarka sukurti šiam stendui."];
    case 2 then
        d.goal="Sujungti nuoseklią RC grandinę ir teisingai įterpti ampermetrą.";
        d.theory=["Nuoseklioje grandinėje rezistoriumi, kondensatoriumi ir ampermetru teka ta pati srovė. Visi keturi pagrindiniai laidai sudaro vieną uždarą kelią nuo generatoriaus išėjimo atgal iki jo grįžimo lizdo.";"Idealiame ampermetre įtampos kritimo nepaisoma. Jis įterpiamas į srovės kelią, o ne prijungiamas tarp generatoriaus gnybtų. Šis vedamasis stendas netinkamos jungties neįrašo ir nurodo reikalingą porą.";"RC kondensatorius nekeičiamas laidu: kondensatoriaus vidinis ryšys priklauso nuo dažnio, jo gnybtai nėra tas pats mazgas. Matavimo lizdai T11/T12 ir T15/T16 šiame sujungimo etape nereikalingi."];
        d.method=["1. [B09] būsena turi būti IŠJUNGTA. Jei jau įjungta, paspauskite B09.";"2. W01: T01 → T05. Spauskite T01, po to T05. generatoriaus išėjimas → ampermetro įėjimas.";"3. W02: T06 → T09. Spauskite T06, po to T09. ampermetro COM → R8 kairysis lizdas.";"4. W03: T10 → T13. Spauskite T10, po to T13. R8 dešinysis lizdas → C2 kairysis lizdas.";"5. W04: T14 → T02. Spauskite T14, po to T02. C2 dešinysis lizdas → generatoriaus grįžimas.";"6. [B10] patikrinkite 4 laidus. Suklydus [B11] atšaukia paskutinį, [B12] išvalo šios dalies laidus.";"7. [B03] galima apžiūrėti atliktą jungimą ir grįžti į savo darbą. [B04], paskui [B36]."];
        d.formulas=["Srovės kelias: T01 → T05 — A~ — T06 → T09 — R8 — T10 → T13 — C2 — T14 → T02.";"ZRC = R8 − j/(2·pi·f·C2). Skaičiuosime E03."];
        d.check=["4 pagrindiniai laidai, nė vieno voltmetro zondo.";"B10 nerodo trūkstamų jungčių; E02 po patikros pažymimas atliktu."];
        d.mistakes=["T09 jau užimtas: kitas laidas jungiamas prie T10, ne dar kartą T09.";"Paspaustas komponento pavadinimas: spauskite patį numeruotą T lizdą.";"Laido nėra: pasirinkti reikia du skirtingus lizdus iš nurodytos poros."];
        d.questions=["Kodėl ampermetras nėra jungiamas lygiagrečiai šaltiniui?";"Kodėl vienodas srovės stipris nereiškia vienodų elementų įtampų?"];
        d.source=["[S1] p. 3, RC darbo 1–2 punktai.";"[S3] matavimo prietaisų nuoseklaus ir lygiagretaus jungimo pagrindai.";"[N] T numeriai ir keturių laidų planas – virtualaus stendo realizacija."];
    case 3 then
        d.goal="Apskaičiuoti RC reaktyviąją varžą, srovę, įtampas, galią ir fazę.";
        d.theory=["Rezistoriaus varža yra reali: ZR = R. Kondensatoriaus varža ZC = −jXC, todėl bendras impedansas Z = R−jXC. XC yra teigiamas talpinės varžos modulis; minusas yra kompleksinėje išraiškoje.";"Bendros varžos modulio negalima gauti sudedant R+XC. Šie dydžiai statmeni kompleksinėje plokštumoje, todėl naudojama kvadratinė šaknis iš kvadratų sumos.";"UR ir UC įtampų fazės skiriasi 90°. Įtampų fazorių suma lygi šaltinio fazoriui; moduliams E = sqrt(UR²+UC²), o ne UR+UC.";"Kondensatorius šiame idealiame modelyje vidutiniškai aktyviosios galios nevartoja. P = I²R yra rezistoriuje išskiriama aktyvioji galia. Visos įtampos ir srovės formulėse yra RMS.";"Šiame atsakymų lape prašoma srovės fazės φI šaltinio įtampos atžvilgiu. RC srovė pirmauja, todėl φI > 0; varžos kampas φZ = −φI."];
        d.method=["1. [B39] nusirašykite savo E_RC, f_RC, R8 ir C2. C2 reikšmę iš µF paverskite į F.";"2. Pagal žemiau pateiktą seką apskaičiuokite XC, |Z|, I, UR8, UC2, P ir φI.";"3. [A03.01–A03.07] įrašykite skaičius etiketėse nurodytais vienetais. I pateikiama mA, P – mW, φI – laipsniais.";"4. [B28] palyginkite su varžų diagrama, [B29] – su įtampų diagrama; jos yra modelio paaiškinimai, ne matavimai.";"5. [B41] trumpai paaiškinkite rezultatus. [B04] patikrinkite skaičius. Jei reikia, [B03] rodo sprendimą jūsų parametrams."];
        d.formulas=["XC = 1/(2·pi·f_RC·C2).";"Z = R8 − jXC; |Z| = sqrt(R8² + XC²).";"I = E_RC/|Z|; į atsakymą I_mA = 1000·I.";"UR8 = I·R8; UC2 = I·XC.";"P = I²·R8; į atsakymą P_mW = 1000·P.";"φI = atan(XC/R8)·180/pi; φZ = −φI."];
        d.check=["Patikra: sqrt(UR8²+UC2²) ≈ E_RC.";"|Z| ≥ R8; I ≤ E_RC/R8; φI tarp 0 ir +90°."];
        d.mistakes=["I per mažas 1000 kartų: į mA lauką neperskaičiuota srovė amperais.";"Gautas neigiamas XC: į XC lauką rašykite modulį, −j yra impedanso žymėjime.";"Fazė radianais: atan rezultatą padauginkite iš 180/pi."];
        d.questions=["Kodėl E nėra lygi UR8+UC2?";"Kas nutiktų XC padidinus dažnį du kartus?"];
        d.source=["[S1] p. 3, RC 3 ir 7 punktai.";"[S4] PD8 teorija: kompleksinė varža ir efektinės vertės.";"[N] aiškiai atskirtos φI ir φZ bei papildytas fazės skaičiavimas."];
    case 4 then
        d.goal="Išmatuoti RC srovę ir tris įtampas; patikrinti fazorinį įtampų balansą.";
        d.theory=["Voltmetras jungiamas lygiagrečiai: jo du zondai turi apimti vieną visą elementą arba šaltinį. T07 yra V~ lizdas, T08 – COM. Tai atskiras prietaisas nuo grandinėje esančio ampermetro.";"R8 matavimo pora T11/T12 elektriškai sutampa su pagrindiniais T09/T10, C2 pora T15/T16 – su T13/T14, o šaltinio T03/T04 – su T01/T02. Todėl voltmetro matavimas pagrindinio laido nenutraukia.";"Pakeitus zondus senasis gyvas skaičius išnyksta. B15 atlieka naują matavimą ir jį išsaugo žurnale. Vien zondų prijungimas nėra matavimas.";"Iš matuotų UR ir UC apskaičiuokite šaltinio RMS įtampą pagal statmenų fazorių sumą. Srovę patikrinkite per rezistorių: I = UR/R8. Idealiame modelyje skirtumai gali kilti tik dėl apvalinimo."];
        d.method=["1. [B09] įjunkite generatorių. [B14] išmatuokite I; rodmuo ir kilmė atsiranda žurnale.";"2. UR8: T07 → T11 ir T08 → T12. [B15] išmatuokite įtampą.";"3. [B13] nuimkite abu V zondus. UC2: T07 → T15 ir T08 → T16. [B15].";"4. [B13]. Šaltinis E: T07 → T03 ir T08 → T04. [B15].";"5. [A04.01] įrašykite sqrt(UR8²+UC2²); [A04.02] įrašykite 1000·UR8/R8.";"6. [B28], [B29], [B30] peržiūrėkite diagramas ir oscilogramą. [B41] atsakykite į klausimus. [B04] patikrinkite."];
        d.formulas=["E_sk = sqrt(UR8_mat²+UC2_mat²).";"I_sk,mA = 1000·UR8_mat/R8.";"δE = 100·(E_sk−E_mat)/E_mat.";"u(t)=sqrt(2)·E·sin(2·pi·f·t); i(t)=sqrt(2)·I·sin(2·pi·f·t+φI)."];
        d.check=["Žurnale turi būti RC I, UR, UC ir UE.";"Du skaitiniai atsakymai apskaičiuoti iš matavimų, ne vien nukopijuoti iš E03."];
        d.mistakes=["NEPRIJUNGTA: patikrinkite abu zondus; vien T07 → T11 nepakanka.";"PARUOŠTA: spauskite B15, o srovei B14.";"Norite keisti UR į UC: B13 nuima tik zondus; pagrindinės grandinės neardykite."];
        d.questions=["Ką oscilogramoje reiškia srovės pirmavimas?";"Ar idealus virtualus matavimas leidžia įvertinti tikro voltmetro paklaidą? Kodėl?"];
        d.source=["[S1] p. 3, RC 4–7 punktai.";"[N] matavimų žurnalas, jų kilmė ir oscilograma – papildymas."];
    else error("Netinkamas metodikos etapas.");
    end
endfunction
