function lines=ld2_method_lines(step)
    global LD2;
    d=ld2_method_data(step);
    lines=[ld2_step_title(step);"VARIANTAS: "+LD2.state.student.variant_id; ...
        ld2_parameter_lines(LD2.cfg);" ";"TIKSLAS";d.goal;" "; ...
        "TEORIJA IR FIZIKINĖ PRASMĖ";d.theory;" ";"DARBO EIGA – KONKRETŪS NUMERIAI";d.method; ...
        " ";"FORMULĖS IR VIENETAI";d.formulas;" ";"KADA ETAPAS ATLIKTAS";d.check; ...
        " ";"DAŽNOS KLAIDOS IR TAISYMAS";d.mistakes;" "; ...
        "KLAUSIMAI SAVO PAAIŠKINIMUI [B41]";d.questions; ...
        " ";"TURINIO KILMĖ";d.source;" ";"BENDROJI ATMINTINĖ";ld2_common_theory()];
endfunction

function ld2_open_method(step)
    global LD2;
    if LD2.ui.headless then return; end
    f=figure("default_axes","off","dockable","off","menubar","none","toolbar","none");
    f.figure_name="LD2 metodika – "+ld2_step_title(step);
    f.axes_size=ld2_aux_size([1040 780]); f.figure_position=[15 15];
    rows=ld2_wrap_lines(ld2_method_lines(step),110);
    uicontrol(f,"style","text","units","normalized","position",[0.025 0.93 0.95 0.045], ...
        "string",ld2_step_title(step)+"  |  "+LD2.state.student.variant_id, ...
        "fontname","Arial","fontunits","pixels","fontsize",17,"fontweight","bold");
    uicontrol(f,"style","listbox","units","normalized","position",[0.025 0.11 0.95 0.80], ...
        "string",rows,"fontname","Arial","fontunits","pixels","fontsize",14, ...
        "backgroundcolor",[1 1 1]);
    uicontrol(f,"style","pushbutton","units","normalized","position",[0.025 0.025 0.22 0.055], ...
        "string","[H01] Ankstesnis etapas","callback",msprintf("ld2_open_method(%d)",max([1 step-1])));
    uicontrol(f,"style","pushbutton","units","normalized","position",[0.265 0.025 0.22 0.055], ...
        "string","[H02] Kitas etapas","callback",msprintf("ld2_open_method(%d)",min([12 step+1])));
    uicontrol(f,"style","pushbutton","units","normalized","position",[0.505 0.025 0.23 0.055], ...
        "string","[H03] Kontaktų žinynas","callback","ld2_show_contact_map()");
    uicontrol(f,"style","pushbutton","units","normalized","position",[0.755 0.025 0.22 0.055], ...
        "string","[H04] Uždaryti","callback",msprintf("ld2_close_aux(%d)",f.figure_id));
endfunction

function ld2_edit_step_note()
    global LD2;
    if LD2.example_active then
        ld2_show_error("Tai pavyzdžio būsena.",["[B03] grįžkite į MANO DARBAS; tada [B41] įrašykite savo paaiškinimą."]); return;
    end
    k=LD2.state.step; d=ld2_method_data(k);
    note=x_dialog([msprintf("[B41] E%02d – jūsų paaiškinimas ataskaitai",k);d.questions; ...
        "Aprašykite formulę, savo veiksmus ir rezultatų prasmę. OK išsaugo, Cancel nekeičia."], ...
        LD2.state.step_notes(k));
    if size(note,"*")==0 then return; end
    LD2.state.step_notes(k)=strcat(matrix(note,-1,1),ascii(10));
    ld2_event("B41","Atnaujintas etapo paaiškinimas.");
    ld2_set_status("E"+msprintf("%02d",k)+" paaiškinimas įrašytas. [B05] išsaugo darbą, [B07] – ataskaitą.","ok");
endfunction

function ld2_show_contact_map()
    ids=ld2_terminal_ids(); lines=emptystr(0,1);
    for k=1:size(ids,"*"); lines($+1,1)=ld2_terminal_name(ids(k)); end
    lines=[lines;" ";"VIDINĖS JUNGTYS (ne papildomi jūsų laidai):"; ...
        "T01 ≡ T03; T02 ≡ T04 (generatorius)."; ...
        "T09 ≡ T11; T10 ≡ T12 (R8). T13 ≡ T15; T14 ≡ T16 (C2)."; ...
        "T17 ≡ T19; T18 ≡ T20 (R9). T21 ≡ T23; T22 ≡ T24 (L1)."; ...
        "T25 ≡ T27 ≡ T37; T26 ≡ T28 (C4)."; ...
        "T29 ≡ T31; T30 ≡ T32 ≡ T38 (L3). T33 ≡ T35; T34 ≡ T36 (R13)."; ...
        "Bendras mazgas tarp C4 ir L3 atsiranda tik sujungus pagrindinį laidą T26–T29."; ...
        "T07 = voltmetro V~; T08 = jo COM. T05 = ampermetro A~; T06 = jo COM."];
    ld2_text_window("[B42] Pastovių kontaktų žinynas",lines);
endfunction

function ld2_show_button_map()
    [ids,cbs,labels,hints]=ld2_button_registry(); lines=emptystr(0,1);
    for k=1:size(ids,"*"); lines($+1,1)="["+ids(k)+"] "+labels(k)+" – "+hints(k); end
    lines=[lines;"E01–E12 – etapų pasirinkimas.";"F01 – sąrašo numeris; F02 – vardas, pavardė; F03 – grupė; F04 – dažnis Hz."; ...
        "A03.01 ir pan. – E03 etapo 1 atsakymo laukas. Jo etiketėje nurodytas vienetas."; ...
        "V01 – dažnio slankiklis; V02 – laisva etapų navigacija."; ...
        "H01/H02 – metodikos ankstesnis/kitas etapas; H03 – kontaktai; H04 – uždaryti pagalbos langą."; ...
        "D numeriai – patvirtinimo dialogų parinktys. Standartinis OK patvirtina, Cancel atšaukia."];
    ld2_text_window("[B45] Valdiklių žinynas",lines);
endfunction

function ld2_show_variant_bank()
    lines=["64 iš anksto nustatyti virtualūs variantai. Bankas LD2-64-A-2026."; ...
        "Nr | R8 Ω; fRC Hz | R9 Ω; fRL Hz | R13 Ω; L3 mH; C4 nF"; ...
        "Visiems: E_RC=E_RL=9 V RMS; C2=4,7 µF; L1=0,5 H; E_RLC=5 V RMS."];
    for n=1:64
        c=ld2_variant_config(n);
        lines($+1,1)=msprintf("%02d | %.0f; %.0f | %.0f; %.0f | %.0f; %.0f; %.0f", ...
            n,c.R8,c.F_RC,c.R9,c.F_RL,c.R13,c.L3*1e3,c.C4*1e9);
    end
    ld2_text_window("[B43] LD2 64 variantai",lines);
endfunction

function ld2_text_window(title,rows)
    global LD2;
    if LD2.ui.headless then return; end
    f=figure("default_axes","off","dockable","off","menubar","none","toolbar","none");
    f.figure_name=title; f.axes_size=ld2_aux_size([980 700]); f.figure_position=[15 15];
    uicontrol(f,"style","listbox","units","normalized","position",[0.025 0.12 0.95 0.85], ...
        "string",ld2_wrap_lines(rows,104),"fontname","Arial","fontunits","pixels","fontsize",14,"backgroundcolor",[1 1 1]);
    uicontrol(f,"style","pushbutton","units","normalized","position",[0.7 0.025 0.27 0.065], ...
        "string","[H04] Uždaryti","callback",msprintf("ld2_close_aux(%d)",f.figure_id));
endfunction

function wh=ld2_aux_size(desired)
    wh=desired;
    try
        sc=get(0,"screensize_px");
        if size(sc,"*")==4 then wh=[min([desired(1) sc(3)-45]) min([desired(2) sc(4)-110])]; end
    catch end
endfunction
