function d=ld2_method_data_9_12(step)
    d=struct("goal", "", "theory",emptystr(0,1), "method",emptystr(0,1), "formulas",emptystr(0,1), "check",emptystr(0,1), "mistakes",emptystr(0,1), "questions",emptystr(0,1), "source",emptystr(0,1));
    select step
    case 9 then
        d.goal="Eksperimentiškai virtualiame modelyje rasti rezonansą pagal UR13 maksimumą.";
        d.theory=["Rezonanso sąlyga XL=XC duoda f0 = 1/(2·pi·sqrt(L3·C4)). Ši teorinė reikšmė yra paieškos orientyras, tačiau matuotas fr gaunamas iš jūsų užfiksuotų taškų."; ...
        "Ties f0 reaktyviosios dalys kompensuojasi, |Z| mažiausias ir lygus R13. Srovė bei UR13 didžiausi. Srovės ir šaltinio įtampos fazės sutampa."; ...
        "Vieno didelio rodmens nepakanka maksimumui pagrįsti: reikia bent vieno taško mažesniu ir vieno didesniu dažniu, kurių UR13 mažesni. Programa reikalauja bent 3 skirtingų dažnių ir maksimumo tarp kraštinių taškų."; ...
        "F04 leidžia įvesti trupmeninį dažnį. V01 slankiklis skirtas apytikslei paieškai, B17–B20 – smulkinimui. Po kiekvieno keitimo būtinas naujas B15 matavimas. B21 negali naudoti pasenusio rodmens."; ...
        "Periodas T_ms = 1000/fr. Tai tas pats ryšys kaip f = 1/T, tik laikas pateiktas milisekundėmis. B30 modelio oscilogramoje galima patikrinti, kokį periodą atitinka nustatytas dažnis."];
        d.method=["1. [B13] nuimkite likusius V zondus. T07 → T35, T08 → T36 – voltmetras apima R13."; ...
        "2. [B09] įjunkite generatorių. Apskaičiuokite teorinį f0 pagal savo L3 ir C4."; ...
        "3. [F04] įrašykite pasirinktą dažnį Hz; [B16] jį taiko. [B15] išmatuokite UR13; [B21] įrašykite tašką."; ...
        "4. Keiskite dažnį ir kartokite B16 → B15 → B21. Artėdami prie maksimumo mažinkite žingsnį; turėkite taškų iš abiejų pusių."; ...
        "5. [B31] rodo būtent jūsų paieškos taškus. [B30] rodo nustatyto dažnio periodą."; ...
        "6. [A09.01] teorinis f0; [A09.02] geriausio užfiksuoto taško fr; [A09.03] 1000/fr; [A09.04] to taško UR13."; ...
        "7. [B41] aprašykite paiešką. [B04] tikrina ir taškus, ir skaičius."];
        d.formulas=["f0 = 1/(2·pi·sqrt(L3·C4))."; ...
        "XL = 2·pi·f·L3; XC = 1/(2·pi·f·C4)."; ...
        "|Z| = sqrt(R13²+(XL−XC)²)."; ...
        "I = E_RLC/|Z|; UR13=I·R13."; ...
        "T_ms = 1000/fr_mat."];
        d.check=["Bent 3 skirtingi užfiksuoti taškai; maksimumas ne intervalo krašte."; ...
        "UR13,max turi būti bent 97 % E_RLC. Tai mokomasis paieškos kriterijus, ne matavimo prietaiso tikslumo specifikacija."; ...
        "Ataskaitoje teorinis f0 ir rastas fr rodomi atskirai."];
        d.mistakes=["B21 sako rodmuo paseno: dažnį jau pakeitėte; dar kartą B15, tada B21."; ...
        "Visi taškai vienoje maksimumo pusėje: išmatuokite ir užfiksuokite tašką kitoje pusėje."; ...
        "Į F04 įrašyta 5 vietoje 5 kHz: F04 reikia 5000."];
        d.questions=["Kaip pagrindžiate, kad rastas taškas yra maksimumas?"; ...
        "Kodėl teorinis ir jūsų rastas fr gali šiek tiek skirtis?"];
        d.source=["[S1] p. 5, RLC 3–4 punktai."; ...
        "[N] paieškos taškų aprėminimas, kilmė ir f0/fr atskyrimas."];
    case 10 then
        d.goal="Atskirai rasti UL ir UC maksimumus bei bendros ULC įtampos minimumą.";
        d.theory=["UL = I·XL, UC = I·XC. Keičiant dažnį keičiasi ne tik srovė, bet ir atitinkamas XL arba XC. Todėl atskiri įtampų maksimumai nebūtinai sutampa su srovės maksimumo dažniu."; ...
        "Šiam idealiam, bet slopinamam RLC modeliui Q = sqrt(L3/C4)/R13. Kai Q>1/sqrt(2), fC = f0·sqrt(1−1/(2Q²)), o fL = f0/sqrt(1−1/(2Q²)). Taigi fC < f0 < fL. Visi 64 variantai parinkti šiai sąlygai."; ...
        "Ties tikslia srovės rezonanso būsena UL ir UC moduliai lygūs, jų fazės priešingos, todėl ULC = |UL−UC| = 0. Bendros reaktyviosios poros įtampos negalima rasti kaip UL+UC."; ...
        "Į atsakymus rašomi jūsų užfiksuoti ekstremumai ir jų dažniai. Jeigu f nėra tiksliai f0, tikras virtualaus prietaiso ULC rodmuo gali būti nedidelis, bet nenulinis. Programa jo nepakeičia teoriniu nuliu."; ...
        "Maksimumų stiprumas priklauso nuo Q; jų įtampos gali viršyti šaltinio įtampą. Tai neprieštarauja Kirchhofo dėsniui, nes sumuojami fazoriai, o ne visi teigiami moduliai."];
        d.method=["1. UL: [B13], tada T07 → T31 ir T08 → T32. [B09] turi būti ĮJUNGTA."; ...
        "2. Keiskite [F04] / [B16]; kiekviename dažnyje [B15] → [B23]. UL reikia bent 3 taškų, iš abiejų rasto maksimumo pusių."; ...
        "3. UC: [B13], T07 → T27 ir T08 → T28. Pakartokite dažnio keitimą → B15 → B23; raskite atskirą maksimumą."; ...
        "4. ULC: [B13], T07 → T37 ir T08 → T38. Taip pat įrašykite bent 3 taškus, dabar ieškokite minimumo."; ...
        "5. [B33] ir lentelėje matysite kiekvieno taikinio geriausią rodmenį su jo dažniu."; ...
        "6. [A10.01–A10.06] įrašykite ULmax, UCmax, ULCmin, fL, fC, fULC. Įtampas ir dažnius imkite iš atitinkamų užfiksuotų taškų."; ...
        "7. [B41] palyginkite fL, fC ir E09 fr. [B04] patikrinkite."];
        d.formulas=["UL = E_RLC·XL/|Z|; UC = E_RLC·XC/|Z|; ULC = |UL−UC|."; ...
        "Q = sqrt(L3/C4)/R13."; ...
        "fL = f0/sqrt(1−1/(2Q²)); fC = f0·sqrt(1−1/(2Q²))."; ...
        "Ties f0: UL = UC = Q·E_RLC; ULC = 0 (teorinis idealus taškas)."];
        d.check=["Kiekvienam taikiniui bent 3 skirtingi dažniai, geriausias taškas tarp mažesnio ir didesnio f."; ...
        "ULCmin ne didesnis kaip 10 % E_RLC; mažesni žingsniai leidžia dar priartėti prie nulio."; ...
        "Atsakymų vertinimo atskaita – užfiksuotų taškų vertės."];
        d.mistakes=["Sumaišyti fL ir fC: UL ieškoma per T31/T32, UC – per T27/T28."; ...
        "Norite matuoti ULC per T31/T28: taip apimami ne tie kraštai; naudokite T37/T38."; ...
        "Išmatuota 0,02 V, bet rašote 0: laukelyje nurašykite matuotą minimumą, o teorinį nulį aptarkite pastaboje."];
        d.questions=["Kodėl UL ir UC atskirų maksimumų dažniai skiriasi?"; ...
        "Kaip gali būti UL > E_RLC, bet bendras fazorių balansas vis tiek galioti?"];
        d.source=["[S1] p. 5–6, RLC 5–7 punktai."; ...
        "[N] tikslios idealaus slopinamo kontūro maksimumų formulės ir jų aiškus atskyrimas."];
    case 11 then
        d.goal="Rasti pusės aktyviosios galios dažnius f1 ir f2, BW ir Q.";
        d.theory=["Rezistoriaus galia P = I²R13. Pusė maksimumo galios atitinka I = Imax/sqrt(2), todėl ir UR13 = UR13,max/sqrt(2). Įtampos lygis yra maždaug 0,7071 maksimumo, ne pusė įtampos."; ...
        "Originalo 8–11 punktai pusės galios ribas siūlo sieti su ritės įtampa. Šiame stende tai aiškiai pakeista: aktyviosios galios ribos nustatomos per R13 įtampą. Ritės įtampa papildomai priklauso nuo dažnio, todėl jos 0,707·UL,max kriterijus nėra tas pats."; ...
        "f1 yra žemiau srovės rezonanso, f2 – aukščiau. Juostos plotis BW = f2−f1; matavimu paremtas kokybės koeficientas Qmat = fr_mat/BW."; ...
        "Kai E09 atliktas, slenkstis nustatomas iš ten užfiksuoto UR13 maksimumo. Laisvai peršokus į E11, orientyras yra nominali E_RLC ir teorinis f0; tai aiškiai pažymima ir ataskaitoje. E09 vis tiek lieka neatliktas."; ...
        "Analitinės ribos pateiktos savikontrolei. Jos nepakeičia reikalavimo B24 ir B25 išsaugoti galiojantį virtualų matavimą abiejose rezonanso pusėse."];
        d.method=["1. [B13]; T07 → T35, T08 → T36. [B09] įjunkite generatorių."; ...
        "2. Lentelėje nusirašykite UR13 slenkstį. Pasirinkite dažnį žemiau fr per F04 ir B16."; ...
        "3. [B15] matuokite ir keiskite f, kol UR13 priartės prie slenksčio. [B24] užfiksuokite f1."; ...
        "4. Dažnį perkelkite aukščiau fr. Kartokite keitimą ir B15. [B25] užfiksuokite f2."; ...
        "5. [A11.01] slenkstis; [A11.02] f1; [A11.03] f2; [A11.04] f2−f1; [A11.05] fr/BW."; ...
        "6. [B41] parašykite, kuo paremti slenkstis ir Q. [B04] tikrinkite."];
        d.formulas=["U_slenkstis = UR13,max/sqrt(2)."; ...
        "f1 = (sqrt(R13²+4L3/C4)−R13)/(4·pi·L3)."; ...
        "f2 = (sqrt(R13²+4L3/C4)+R13)/(4·pi·L3)."; ...
        "BW_teor = R13/(2·pi·L3); Q_teor = f0/BW_teor."; ...
        "BW_mat = f2_mat−f1_mat; Q_mat = fr_mat/BW_mat."];
        d.check=["Yra abu matavimo mygtukais užfiksuoti taškai ir f1 < fr < f2."; ...
        "B24/B25 leidžia iki 3 % slenksčio rodmens skirtumą; tai mokomasis paieškos kriterijus."; ...
        "Tik įrašytų teorinių f1/f2 į laukus nepakanka."];
        d.mistakes=["B24 atmeta dažnį: tikrinkite, ar jis tikrai žemiau fr. B25 naudojamas virš fr."; ...
        "Pakeitę dažnį nespaudėte B15: fiksuojamas tik naujas matavimas."; ...
        "Naudojate 0,5·URmax: pusės galios įtampos kriterijus 1/sqrt(2)."];
        d.questions=["Kodėl pusės galios įtampa nėra pusė maksimalios įtampos?"; ...
        "Kaip didesnis R13 keistų rezonanso kreivės plotį?"];
        d.source=["[S1] p. 6, RLC 8–11 punktai."; ...
        "[N] metodinis pakeitimas – pusės aktyviosios galios kriterijus pagal UR13; BW ir Q papildyti."];
    case 12 then
        d.goal="Sudaryti dažninę lentelę, apibendrinti rezultatus ir išsaugoti detalų darbą.";
        d.theory=["Dažninė charakteristika parodo, kaip UR13 priklauso nuo generatoriaus dažnio. Originalaus aprašo lentelėje naudojami 0, 1, 2, ..., 10 kHz taškai; toks žingsnis gali nepagauti siauro maksimumo, todėl iš E09 turimi papildomi paieškos taškai yra svarbūs."; ...
        "B26 vykdo virtualių 1–10 kHz matavimų seką su tuo pačiu modeliu ir tikrintuvu. 0 Hz nėra sinusinis AC signalas: jo eilutė pažymėta kaip teorinė ribinė vertė UR13 → 0. Ji nepateikiama kaip voltmetro matavimas."; ...
        "Ataskaita atskiria priskirtus parametrus, studento tekstą, teorinę atskaitą, virtualius matavimus, užfiksuotus ekstremumus, klaidų žurnalą ir atliktus/praleistus etapus. Pavyzdžio duomenys neperrašomi kaip studento matavimai."; ...
        "B07 generuoja savarankišką HTML dokumentą su lentelėmis ir diagramomis, CSV duomenimis ir .sod tęsimo failu. HTML galima atverti naršyklėje be interneto; naršyklės spausdinimo lange galima pasirinkti PDF. Tai nėra automatinis PDF spausdintuvo valdymas iš Scilab."; ...
        "Ataskaita nėra galutinis pažymys. Skaitinė savikontrolė ir atlikimo būsenos padeda dėstytojui, tačiau kokybinius paaiškinimus ir išvadas vertina dėstytojas."];
        d.method=["1. [B13]; T07 → T35, T08 → T36. [B09] įjunkite generatorių."; ...
        "2. [B26] atlikite 0–10 kHz skenavimą. Patikrinkite visas 11 eilučių ir kilmės stulpelį."; ...
        "3. [B31] atverkite lentelės grafiką. [B33] – visą matavimų žurnalą, [B34] – atsakymų suvestinę."; ...
        "4. [B41] aprašykite šio etapo kreivę. [B08] įrašykite bendras darbo išvadas: RC/RL fazės, fazorių sumos, fr, įtampų maksimumai, BW ir Q."; ...
        "5. [B04] patikrinkite E12. Kai visi etapai patikrinti ir užpildyti studento duomenys bei išvados, programa pasiūlo išsaugoti galutinę ataskaitą."; ...
        "6. [B07] bet kada sugeneruoja ataskaitą: neužbaigto darbo dokumentas aiškiai pažymimas JUODRAŠTIS. Pasirinkite aplanką."; ...
        "7. Atverkite nurodytą ATASKAITA.html, patikrinkite variantą, savo tekstą ir matavimus. Pateikite dėstytojui visą sugeneruotą aplanką arba HTML su priedais."];
        d.formulas=["UR13(f) = E_RLC·R13 / sqrt(R13²+(2·pi·f·L3−1/(2·pi·f·C4))²), kai f>0."; ...
        "Riba f→0+: UR13→0."; ...
        "Δ = studento rezultatas − atskaitos rezultatas; δ = 100·Δ/atskaita, tik kai atskaita nelygi nuliui."];
        d.check=["11 skenavimo eilučių; 0 Hz eilutė aiškiai teorinė."; ...
        "Ataskaitoje yra sąrašo numeris, LD2-Vnn, priskirti parametrai, 12 etapų būsenos ir išvados."; ...
        "Neatliktas rodmuo rašomas NEATLIKTA, ne 0 ir ne teorinis skaičius."];
        d.mistakes=["B26 neleidžia skenuoti: B09 įjungta ir V zondai T07–T35/T08–T36 turi būti prijungti."; ...
        "Ataskaita JUODRAŠTIS: patikrinkite nepabaigtų etapų sąrašą, F02/F03 ir B08 išvadas."; ...
        "Neturite rašymo teisių: B07 pasirinkite savo Dokumentų aplanką, ne Program Files."];
        d.questions=["Kodėl 1 kHz žingsnio lentelė gali nepataikyti į rezonansą?"; ...
        "Kuri jūsų ataskaitos dalis gauta matuojant, o kuri – skaičiuojant?"; ...
        "Kokie modelio ribotumai trukdo šiuos skaičius laikyti realaus modulio matavimais?"];
        d.source=["[S1] p. 6, RLC 12–13 punktai ir išvados."; ...
        "[N] ataskaita, žurnalas, individualūs variantai, savikontrolė ir duomenų kilmė."];
    else error("Netinkamas metodikos etapas.");
    end
endfunction
